name: epub_view
description: Flutter widget for view EPUB documents on on Web, MacOs, Android and iOS. Based on dart-epub package.
repository: https://github.com/ScerIO/packages.flutter/tree/main/packages/epub_view
issue_tracker: https://github.com/ScerIO/packages.flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+epub_view%22
version: 3.2.0

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  epubx:
    git:
      url: https://github.com/tourlivecokr/epubx.dart.git
  equatable: ^2.0.5
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  scrollable_positioned_list: ^0.3.8
  collection: ^1.17.1
  universal_file: ^1.0.0
  easy_image_viewer: ^1.5.1
  flutter_soloud: ^3.1.7
  chewie: ^1.11.3
  video_player: ^2.9.5
  dio: ^5.8.0+1
  intl: ^0.19.0
  mixpanel_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  assets:
    - assets/images/
